Adding a tv radio blog and fixing one of johns links
devedmonton/codevid19.com pull request #105
Opened 2020-04-24 05:18 UTC by MandyMeindersma

2020-04-24 05:19 UTC, MandyMeindersma commented
I should have created this as a draft, oops. For whatever reason my local won't create the blog post, want to see if netlify will fix it for me

2020-04-24 05:20 UTC, MandyMeindersma commented
It didn't.... I must be typing something wrong, anyone see my mistake?

2020-04-24 14:03 UTC, johnny-newton commented
Maybe found your typing issue.I don't know how to mark up your code to point this out, so I'll dump it into this message-sorry. I noticed that the link to the charity shop exchange website looks off it should be (https://charityshopexchange.com) but there is some html in there.  The link is 404 

j

> On Apr 23, 2020, at 11:20 PM, Mandy Meindersma <notifications@github.com> wrote:
> 
> 
> It didn't.... I must be typing something wrong, anyone see my mistake?
> 
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub <https://github.com/devedmonton/codevid19.com/pull/105#issuecomment-618807446>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AO3MP32ABLHUNT2LDNIX7A3ROEOSXANCNFSM4MPZMIBQ>.
>

2020-04-24 14:21 UTC, MandyMeindersma commented
@johnny-newton  I didn't do their website link, I was trying to link it to your Q and A blog post

2020-04-24 15:26 UTC, johnny-newton commented
Yup, not a programmer, sorry it was the only thing I noticed.  I wish I could be more help here.  

j

> On Apr 24, 2020, at 8:21 AM, Mandy Meindersma <notifications@github.com> wrote:
> 
> 
> @johnny-newton <https://github.com/johnny-newton> I didn't do their website link, I was trying to link it to your Q and A blog post
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/devedmonton/codevid19.com/pull/105#issuecomment-619040078>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AO3MP33PSY2JQ3KERIXGN43ROGN6VANCNFSM4MPZMIBQ>.
>

2020-04-24 15:27 UTC, MandyMeindersma commented
Hahaha don't be sorry! You are awesome!

On Fri., Apr. 24, 2020, 9:26 a.m. John Newton, <notifications@github.com>
wrote:

> Yup, not a programmer, sorry it was the only thing I noticed. I wish I
> could be more help here.
>
> j
>
> > On Apr 24, 2020, at 8:21 AM, Mandy Meindersma <notifications@github.com>
> wrote:
> >
> >
> > @johnny-newton <https://github.com/johnny-newton> I didn't do their
> website link, I was trying to link it to your Q and A blog post
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub <
> https://github.com/devedmonton/codevid19.com/pull/105#issuecomment-619040078>,
> or unsubscribe <
> https://github.com/notifications/unsubscribe-auth/AO3MP33PSY2JQ3KERIXGN43ROGN6VANCNFSM4MPZMIBQ
> >.
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/devedmonton/codevid19.com/pull/105#issuecomment-619079509>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEFGPY2ZXFSWQJE7RUG5RMDROGVSLANCNFSM4MPZMIBQ>
> .
>

2020-04-24 15:28 UTC, ajyong commented
It's a good thing to notice and fix other bugs too :)

If no one else gets to it, I can squeeze in some lunch time to take a look
today.

On Fri, Apr 24, 2020 at 9:26 AM John Newton <notifications@github.com>
wrote:

> Yup, not a programmer, sorry it was the only thing I noticed. I wish I
> could be more help here.
>
> j
>
> > On Apr 24, 2020, at 8:21 AM, Mandy Meindersma <notifications@github.com>
> wrote:
> >
> >
> > @johnny-newton <https://github.com/johnny-newton> I didn't do their
> website link, I was trying to link it to your Q and A blog post
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub <
> https://github.com/devedmonton/codevid19.com/pull/105#issuecomment-619040078>,
> or unsubscribe <
> https://github.com/notifications/unsubscribe-auth/AO3MP33PSY2JQ3KERIXGN43ROGN6VANCNFSM4MPZMIBQ
> >.
> >
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/devedmonton/codevid19.com/pull/105#issuecomment-619079509>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABQKQNI3536TZ7JALNXR2R3ROGVSLANCNFSM4MPZMIBQ>
> .
>

2020-04-24 16:41 UTC, johnny-newton commented
I'd appreciate having your eyes on it, Mandy just saved me from committing a change to one of my files on the wrong branch.  

> On Apr 24, 2020, at 9:28 AM, Aaron Yong <notifications@github.com> wrote:
> 
> 
> It's a good thing to notice and fix other bugs too :)
> 
> If no one else gets to it, I can squeeze in some lunch time to take a look
> today.
> 
> On Fri, Apr 24, 2020 at 9:26 AM John Newton <notifications@github.com>
> wrote:
> 
> > Yup, not a programmer, sorry it was the only thing I noticed. I wish I
> > could be more help here.
> >
> > j
> >
> > > On Apr 24, 2020, at 8:21 AM, Mandy Meindersma <notifications@github.com>
> > wrote:
> > >
> > >
> > > @johnny-newton <https://github.com/johnny-newton> I didn't do their
> > website link, I was trying to link it to your Q and A blog post
> > >
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly, view it on GitHub <
> > https://github.com/devedmonton/codevid19.com/pull/105#issuecomment-619040078>,
> > or unsubscribe <
> > https://github.com/notifications/unsubscribe-auth/AO3MP33PSY2JQ3KERIXGN43ROGN6VANCNFSM4MPZMIBQ
> > >.
> > >
> >
> > —
> > You are receiving this because your review was requested.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/devedmonton/codevid19.com/pull/105#issuecomment-619079509>,
> > or unsubscribe
> > <https://github.com/notifications/unsubscribe-auth/ABQKQNI3536TZ7JALNXR2R3ROGVSLANCNFSM4MPZMIBQ>
> > .
> >
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/devedmonton/codevid19.com/pull/105#issuecomment-619080577>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AO3MP37WJDSBLWEGDXZXI7LROGVZHANCNFSM4MPZMIBQ>.
>

2020-04-24 19:16 UTC, johnny-newton commented
hold off on this for a moment-I'm waiting for an address/ok from Blake-

> On Apr 24, 2020, at 10:41 AM, John Newton <jjnewto0@ualberta.ca> wrote:
> 
> I'd appreciate having your eyes on it, Mandy just saved me from committing a change to one of my files on the wrong branch.  
> 
>> On Apr 24, 2020, at 9:28 AM, Aaron Yong <notifications@github.com <mailto:notifications@github.com>> wrote:
>> 
>> 
>> It's a good thing to notice and fix other bugs too :)
>> 
>> If no one else gets to it, I can squeeze in some lunch time to take a look
>> today.
>> 
>> On Fri, Apr 24, 2020 at 9:26 AM John Newton <notifications@github.com <mailto:notifications@github.com>>
>> wrote:
>> 
>> > Yup, not a programmer, sorry it was the only thing I noticed. I wish I
>> > could be more help here.
>> >
>> > j
>> >
>> > > On Apr 24, 2020, at 8:21 AM, Mandy Meindersma <notifications@github.com <mailto:notifications@github.com>>
>> > wrote:
>> > >
>> > >
>> > > @johnny-newton <https://github.com/johnny-newton <https://github.com/johnny-newton>> I didn't do their
>> > website link, I was trying to link it to your Q and A blog post
>> > >
>> > > —
>> > > You are receiving this because you were mentioned.
>> > > Reply to this email directly, view it on GitHub <
>> > https://github.com/devedmonton/codevid19.com/pull/105#issuecomment-619040078 <https://github.com/devedmonton/codevid19.com/pull/105#issuecomment-619040078>>,
>> > or unsubscribe <
>> > https://github.com/notifications/unsubscribe-auth/AO3MP33PSY2JQ3KERIXGN43ROGN6VANCNFSM4MPZMIBQ <https://github.com/notifications/unsubscribe-auth/AO3MP33PSY2JQ3KERIXGN43ROGN6VANCNFSM4MPZMIBQ>
>> > >.
>> > >
>> >
>> > —
>> > You are receiving this because your review was requested.
>> > Reply to this email directly, view it on GitHub
>> > <https://github.com/devedmonton/codevid19.com/pull/105#issuecomment-619079509 <https://github.com/devedmonton/codevid19.com/pull/105#issuecomment-619079509>>,
>> > or unsubscribe
>> > <https://github.com/notifications/unsubscribe-auth/ABQKQNI3536TZ7JALNXR2R3ROGVSLANCNFSM4MPZMIBQ <https://github.com/notifications/unsubscribe-auth/ABQKQNI3536TZ7JALNXR2R3ROGVSLANCNFSM4MPZMIBQ>>
>> > .
>> >
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub <https://github.com/devedmonton/codevid19.com/pull/105#issuecomment-619080577>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AO3MP37WJDSBLWEGDXZXI7LROGVZHANCNFSM4MPZMIBQ>.
>> 
>

2020-04-24 20:02 UTC, ajyong commented
@MandyMeindersma it's not appearing because the date in the filename is in the future by 1 day: `2020-04-25`

When I changed it to today's date `2020-04-24` it appeared:
<img width="945" alt="image" src="https://user-images.githubusercontent.com/6334517/80252275-3bec8880-8634-11ea-808c-4a0dd8eb8061.png">

2020-04-24 20:06 UTC, ajyong reviewed
LGTM after changing the filename

2020-04-24 20:06 UTC, ajyong commented on _posts/2020-04-25-TV+Radio.md
> +title: We have been on TV and the Radio talking about how awesome our hackers are!
The title is a bit long but that's okay

2020-04-24 20:06 UTC, ajyong commented on _posts/2020-04-25-TV+Radio.md
> +---
Date in filename should be changed to `2020-04-24` for it to get picked up and rendered

2020-04-24 20:08 UTC, ajyong requested changes

2020-04-24 20:08 UTC, ajyong commented on _posts/2020-04-25-TV+Radio.md
> +We also we featured on Global Edmonton to explain a little bit about what a hackathon is! Even one of our weekly winners Blake Prouty from [Charity Shop Exchange](2020/04/07/charity-shop-exchange.htm
>We also we featured

I think this should be: We were also featured

2020-04-24 21:30 UTC, MandyMeindersma commented
LOL I ACTUALLY THOUGHT IT WAS THE 25 oops. I EVEN SAID THAT IN THE MEETING LOL

2020-04-24 21:31 UTC, MandyMeindersma commented
I have to test some of the links before it goes out, I'll do that tonight and make copy changes

2020-04-25 02:57 UTC, ajyong approved these changes
LGTM :shipit:

2020-04-25 03:06 UTC, merged

2020-04-25 03:06 UTC, johnnewton-hub approved these changes
If it's good enough for Aaron, it's more than good enough for me.  Squash

2020-04-25 03:06 UTC, johnnewton-hub commented on _posts/2020-04-07-charity-shop-exchange.md
> -A large helping of thank-you to [Blake Prouty](https://twitter.com/BlakeNthaniel) for giving us insight into his team’s [Charity Shop Exchange](https://charityshopexchange.com) project. Blake is an u
Hi @ajyong , I can make this change, I just don't know which branch to commit to.  Congratulations on your new gig too btw!

2020-04-25 03:06 UTC, johnnewton-hub commented on _posts/2020-04-07-charity-shop-exchange.md
> -A large helping of thank-you to [Blake Prouty](https://twitter.com/BlakeNthaniel) for giving us insight into his team’s [Charity Shop Exchange](https://charityshopexchange.com) project. Blake is an u
here is the link that Blake would like:  https://www.linkedin.com/mwlite/in/blakenp - checked it, it works...

j-rock