Add contribution rules
devedmonton/codevid19.com pull request #67
Opened 2020-04-10 02:42 UTC by ajyong

This came out of my video call with @johnny-newton.  The link from README.md to CONTRIBUTING.md won't work until this PR has been merged in.

2020-04-10 04:01 UTC, johnnewton-hub approved these changes
This looks good-thanks for the reviewer role practice. jn

2020-04-10 13:53 UTC, MarkBennett requested changes
This is a great start @ajyong.

Can we add a discussion of IP ownership and note that all content must be released to Dev Edmonton Society and will be released under the CC SA 4.0 license.

2020-04-10 14:04 UTC, johnny-newton commented
Do I need to add my own personal licence.  I'm not worried personally-but it might make me look more legit ;  )

2020-04-12 15:36 UTC, MarkBennett approved these changes
Looks good. Ship it! 🚀

2020-04-12 15:36 UTC, MarkBennett commented on CONTRIBUTING.md
> +- By contributing to this repository, you are agreeing to release ownership of the intellectual property of the contributions we accept from you to Dev Edmonton Society
👍

2020-04-12 15:36 UTC, MarkBennett commented on CONTRIBUTING.md
> +- Your contributions will be licensed under Creative Commons Attribution-Sharealike 4.0.  See our [license](https://github.com/devedmonton/codevid19.com/blob/master/LICENSE.txt) for more information.
👍

2020-04-12 18:24 UTC, merged