Reflow landing, move Join the Fight out
devedmonton/codevid19.com pull request #73
Opened 2020-04-11 23:49 UTC by ajyong

- Move Join the Fight to a separate page
- Moved Mailing List to the bottom
- Updated background styles so they alternate
- Sponsor CTA tweaked

I made effectively zero change to the Join the Fight copy, besides renaming the first header (because our `default` template already creates a title for us).

## Before and Afters
### Hero
<img width="1444" alt="image" src="https://user-images.githubusercontent.com/6334517/79057213-0a2ef700-7c1c-11ea-85c9-9beb31f8b07c.png">
<img width="1444" alt="image" src="https://user-images.githubusercontent.com/6334517/79057217-16b34f80-7c1c-11ea-9540-c33ebc14904d.png">

## Join the Fight
<img width="1443" alt="image" src="https://user-images.githubusercontent.com/6334517/79057259-86c1d580-7c1c-11ea-8104-ba10b0561690.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/6334517/79057224-2fbc0080-7c1c-11ea-9518-1b087fee7911.png">

## Become a Sponsor CTA
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/6334517/79057260-90e3d400-7c1c-11ea-853d-af3762387d38.png">
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/6334517/79057244-5f6b0880-7c1c-11ea-9728-2170281df181.png">

2020-04-11 23:55 UTC, ajyong commented
This is a task in [ch804].

Also hurray!  We now have **Deploy Previews** that take <30s to build when PRs are submitted to the `master` branch of this repo!  Click **Details** beside "Deploy preview ready!" to see the changes.
<img width="705" alt="image" src="https://user-images.githubusercontent.com/6334517/79057304-36974300-7c1d-11ea-9aad-7890961d0aa9.png">

Or click [here](https://deploy-preview-73--codevid-19-staging.netlify.com/) but this will be the first and last time I link to a link that's already made for us.

2020-04-12 16:02 UTC, MandyMeindersma commented
This is where the become a sponsor link takes me: Why is it so low? It shouldn't be? (I am on mac)
![image](https://user-images.githubusercontent.com/17459171/79073596-b7e5e880-7ca4-11ea-88ce-25785049726d.png)


Same problem on mobile (android).

2020-04-12 16:04 UTC, MandyMeindersma requested changes
everything looks good except for how sponsorshop href acts, what I am confused about is why it is acting like that, it shouldn't....

2020-04-12 16:22 UTC, MandyMeindersma commented
I played around on your branch, we could just add some margin top and call it good if you want?

2020-04-12 18:26 UTC, ajyong commented
> everything looks good except for how sponsorshop href acts, what I am confused about is why it is acting like that, it shouldn't....

Oof, yeah I noticed this maybe once or twice but thought it was me scrolling manually after the fact.  I think I can do this without adding extra margin/padding... leave it with me and I'll tinker with this a bit more.

2020-04-12 18:52 UTC, ajyong commented
There was a question about the removal of the Home link in #74 [here](https://github.com/devedmonton/codevid19.com/pull/74#pullrequestreview-391873987).  As part of #74, "Home" was re-added in place of "Join the Fight".  However, here are a couple reasons why "Home" was removed in this PR:
1. **CODEVID-19** in the header links to home.  It's may not be immediately obvious to some, but I feel there's been enough user training on the web to cause users to try clicking on logos/links when there's a lack of a home link.
1. "Join the Fight" will be splitting off into its own page.
1. On mobile, going beyond 3 short links causes the issue shown at the start of this PR.  Having to pick 3, "Home" was the first on the chopping block out of the remaining 3.

2020-04-12 21:26 UTC, ajyong commented
It's because of the "fade in and upwards" effect: the smooth-scroller detects the heading position while it's at the start of the animation. 🤦 If you manually scroll back up to the top after all the animations are done and click the "Become a Sponsor" again, it will look a bit better.  Not that anyone actually does that when they're browsing!

I've moved the anchor ID to an `<hr />` just above the real heading to trick the scroller.  It looks and works well on desktop, tablet and mobile now without looking like a hack.

![image](https://user-images.githubusercontent.com/6334517/79080426-fb0a8080-7cd1-11ea-82be-c61bddf462d7.png)

2020-04-13 03:47 UTC, MandyMeindersma commented
ugh sorry last nit pick, I should have done these all at once...

Could we add the same buttons to the join the fight sponsorship section as the sponsorship section:
![image](https://user-images.githubusercontent.com/17459171/79090516-32475480-7d07-11ea-9eb5-3069641cd2c3.png)


Normally I say no to duplication but in the case of money I am all down for duplication

2020-04-13 03:48 UTC, MandyMeindersma requested changes
sorry just one last thing with the two buttons on join the fight sponsorship section

2020-04-13 03:56 UTC, ajyong commented
I want to say no, because we need the third "spot" in the hero buttons section for a link to the Blog eventually.

2020-04-13 04:12 UTC, MandyMeindersma approved these changes

2020-04-13 04:17 UTC, merged