Add Prettier extension to remote container
devedmonton/codevid19.com pull request #76
Opened 2020-04-12 07:06 UTC by ajyong

`devcontainer.json` got formatted by... prettier.

2020-04-12 15:22 UTC, MarkBennett requested changes
Cool idea @ajyong 

Can you just clarify when this will format to code? With this installed are files formatted on save, or do you need to trigger the add-on?

2020-04-12 18:34 UTC, ajyong commented
By default it does nothing.  I think I should add some instructions in the README to:

1. Make Prettier the default formatter
1. Clarify that it formats per-file, on-save if this is enabled in VS Code

2020-04-12 20:46 UTC, ajyong commented
It's more heavy-handed now, and I've added documentation in the README to reflect this.  By default, this PR sets the remote container to:

- Use Prettier as the **default formatter**
- Format your files **on save**
- Trim trailing whitespace from all files **except Markdown**

Give your container a rebuild and let me know if it impedes your workflow @MarkBennett, otherwise I think these "sane defaults" will increase consistency moving forward.

2020-04-13 03:40 UTC, MandyMeindersma commented
lgtm, I will let mark decide on final approval

2020-04-13 16:14 UTC, MarkBennett approved these changes
These changes look like a good start with Prettier @ajyong. Let's try them out and revise if needed.

2020-04-13 16:14 UTC, MarkBennett commented on README.md
> +- Use Prettier as the **default formatter**
Sounds good to me!

2020-04-13 20:44 UTC, merged